spring:
  application:
    name: 'users-service'
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/db_users
    username: db_users
    password: db_users
