spring:
  application:
    name: 'users-service'
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db-users-service:5432/db_users
    username: db_users
    password: db_users
