spring:
  application:
    name: 'provas-service'
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54322/db_provas
    username: db_provas
    password: db_provas
