spring:
  application:
    name: 'provas-service'
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres-2
    username: postgres
    password: postgres
