spring:
  application:
    name: 'provas-service'
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db-provas-service:5432/db_provas
    username: db_provas
    password: db_provas
